site_name: KALXR
site_description: KALXR 的个人网站

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

nav:
  - 主页: index.md
  - 爱好: interests/index.md
  - 随笔: notes/index.md
  - Nikon记忆: photos/index.md
  - 关于我: about/index.md

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search:
      enabled: false

extra_css:
  - stylesheets/extra.css
  - stylesheets/home.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/home.js
  - javascripts/photos.js

extra:
  generator: false
